### Make a order
POST http://localhost:3000/orders/create
content-type: application/json

{
    "orders": [
    {
        "pizzaId": "65303f3053be4b73671931ca",
        "quantity": 5
    }]
}

### Change order status
PATCH http://localhost:3000/orders/edit
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImZ1bGxOYW1lIjoiS3Jhc2kgR2VuY2hldiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5NzE0NDcxNiwiZXhwIjoxNjk3MTUwNzE2fQ.SwtuyJtCFzOFtDlIU2-nkG0w_VgR4_88qmjCWb2myPo

{
    "id": 16,
    "status": "compleated"
}